### PR TITLE
Support of pseudo-streaming

### PR DESCRIPTION
**Pull request by ange007**
Support of pseudo-streaming.
( manual transfer under the latest version. I hope everything correctly )

### CODE REVIEW

**Comment by ange007** [comment]
Didn't forget about this functionality?

**Comment by seniorflexdeveloper** [comment]
@ange007 - Can you tell me which vendor's implementation you used and if you have any test streams which we can test this out on? Thanks.

**Comment by ange007** [comment]
It is possible to test here: http://jsdo.it/ange305/5IHE

**Comment by ange007** [comment]
What thoughts on this function?

**Comment by heff** [comment]
We really appreciate your work on this Vladimir. Looking at the demo you have set up, it does appear to solve the problem of skipping ahead in the Flash video without waiting for the buffer.

This is a difficult one because it adds complexity to some very important operations in the Flash player (play/seek) and we need to do some heavy testing on it to make sure it does not affect playback in other use cases. We would also need other contributors who are more familiar with Flash to take time and review the code. We've also run into some security issues with similar string parameters being passed to Flash, and we would need to make sure these get updated to also be secure.

If we can get one of the other contributors, like @seniorflexdeveloper or even @alemay to review this we might be able to move it forward, but I can't promise anything. I hope we can because it's obvious you've put a lot of work into it.

**Comment by githubzhaoqian** [comment]
That's great, but I don't know whether they have been integrated and distribution.

**Comment by hubertperron** [comment]
@ange007 i'm trying to get your example working on a flv file that do not use milliseconds but keyframes position for the pseudoStreamStartParamType.

Speaking of the pseudoStreamStartParamType, what are the supported options?

**Comment by ange007** [comment]
@hubertperron 
**pseudoStreamStartParamType** is 'bytes' or 'seconds'.
https://github.com/videojs/video.js/pull/1742/files

**Comment by forbesjo** [comment]
Thank you for this PR but we feel that this is more than we would be able to support at this time.

**Pull request closed without merging**
