### PR TITLE
Add event DimensionChange, fix with video 100x100 

### PR DESCRIPTION
**Pull request by digitalStyx**
FIX problem https://github.com/videojs/video-js-swf/issues/55

### CODE REVIEW

**Comment by nicklive** [comment]
Hi, guys! Any plans to merge this request?

**Comment by gkatsev** [comment]
We would really like to verify it but don't have any samples that we can reproduce the issue with, unfortunately.

**Comment by nicklive** [comment]
How I can help? Maybe I can create a public rtmp-stream for you?

**Comment by gkatsev** [comment]
If you can make a test stream that showcases the issue, that would be amazing!

**Comment by nicklive** [comment]
I have prepared an public rtmpt link with "big buck bunny"
(I try to test this stream here https://www.wowza.com/testplayers and it's ok)

I created test page with cdn-hosted videojs-flash@2.1.1 with this link
`rtmpt://95.172.37.254:81/qligentPlayer/stream_1`
and have this result: [image](https://imgur.com/a/nmFcDDC)
Please make your tests with this stream and tell me the results.

**Comment by gkatsev** [comment]
Awesome, thanks @nicklive. I was able to verify the change. Also, any tips for creating local rtmp streams for testing?

**Pull request closed without merging**
