### PR TITLE
Broadcacst cuepoints to External Interface

### PR DESCRIPTION
**Pull request by cladera**
Cuepoints injected in live streams were not broadcasted to External Interface.
This change will allow developers to handle timed-metada injected in RTMP live streams.

### CODE REVIEW

**Comment by cladera** [comment]
I'm struggling on designing tests for this feature. My approach would be to assert the "cuepoint" event is fired when a cue is found in a RTMP stream. However, I'd either need a reliable live feed sending cuepoints periodically which I failed to found; or create a RTMP mock which I have no idea how to deal with. 

May someone help me out with this one?

**Comment by gkatsev** [comment]
Unfortunately, I'm unable to test this so cannot accept the changes. Considering that Google Chrome will soon be disabling flash by default really soon, I don't think it's a huge loss.

**Comment by gkatsev** [comment]
I wanted to add that if we can figure out how to test it, we can reconsider adding it in.

**Comment by cladera** [comment]
@gkatsev You mean test it manually? Or design an unit test?

**Comment by gkatsev** [comment]
Manually. Unit tests would be awesome but this project doesn't really have them, unfortunately.

**Comment by cladera** [comment]
Testing this feature even manually might be tricky. The only way I came up with was to publish a live stream using a custom AMS/Wowza application which would inject cuepoints into the stream every few seconds. Injecting timed-metadata into the stream is part of the core of our player at [webcastudio.com](http://webcastudio.com) so for us is pretty easy to set up.
However, I totally agree with you, I don't see the point of investing more time in this when Flash is about to be executed ;)

**Pull request closed without merging**
