### PR TITLE
onTextData Event

### PR DESCRIPTION
**Pull request by alex-phillips**
Added onTextData event to Flash code for closed captioning support form media server streams (reference: http://help.adobe.com/en_US/ActionScript/3.0_ProgrammingAS3/WSD30FA424-950E-43ba-96C8-99B926943FE7.html)

### CODE REVIEW

**Comment by alex-phillips** [comment]
I'm a little confused on what I need to change in the main `video.js` repo per the contributing guidelines. It seems that `video-js.swf` does not exist inside of that repo. Please advise what changes to make on the main repo and I'll get it done. Thanks!

**Comment by forbesjo** [comment]
Looks like you're missing changes to the action script files? Can you double check to make sure you don't have any uncommitted changes and don't commit the dist folder. Thanks!

**Comment by alex-phillips** [comment]
@forbesjo Sorry, I had committed to the wrong branch on my end. The updates should now be in this PR. Thanks for checking this out!

**Comment by alex-phillips** [comment]
@forbesjo Is there any update on this?

**Comment by forbesjo** [comment]
Sorry, for the delay we will test this along with https://github.com/videojs/video.js/pull/2748 and bring in your changes. Thanks

**Comment by alex-phillips** [comment]
@forbesjo Perfect, thanks!

**Comment by gkatsev** [comment]
LGTM.

**Pull request merged**
