### PR TITLE
Add Stage Video compatibility

### PR DESCRIPTION
**Pull request by benjipott**
#Limitations

With stage video, the video is rendered onto a flash.media.StageVideo object rather than a Video object. The StageVideo object is always shown in a window-aligned rectangular region of the screen. Other graphics may be layered on top of the StageVideo object, but it is not possible to layer objects behind the video. Because StageVideo does not sit in the traditional display list but is composited through the GPU, the following features are not available when the StageVideo object is used:

The StageVideo object cannot be rotated. Only orthogonal rotations (rotations in ninety-degree increments) are possible.
The StageVideo object may not have a colorTransform or 3D transformations transform applied to it. It may not have a matrix transform applied that skews the video.
The StageVideo object cannot have an alpha channel, blendMode, filter, mask, or scale9Grid applied to it.
The video data cannot be copied into a BitmapData object (BitmapData.draw).
The video cannot be bitmap-cached.
The video data must not be embedded in the SWF file. StageVideo can be used only with videos originating from a NetStream object.
Depending on the underlying hardware, some color spaces may not be supported. In such cases, Flash Player will choose a substitute color space. The new StageVideo ActionScript API provides a means to query the color space that is being used.
Depending on the platform, the number of videos you are allowed to display in the video plane is limited. On most mobile systems, only one video is allowed at any time globally. That means that if you have several instances of SWF files showing at the same time, only the first SWF file will be able to display video in a hardware-accelerated fashion.
To ensure compatibility between Flash Player on desktop and on TV devices, set wmode to direct.
Avoid layering wmode="transparent" SWFs on top of each other. Platforms such as Google TV do not support wmode="transparent". This means that all SWF instances are supported when wmode="window" regardless of the <embed> tag parameters.

related doc : 
http://www.adobe.com/devnet/flashplayer/articles/stage_video.html
related issue:
#103

### CODE REVIEW

**Comment by heff** [comment]
Thanks for the PR! Would we see enough benefit from adding stage video to justify the added complexity? And does this PR make it so only stage video is used, or just when it's supported?

**Comment by bdeitte** [comment]
This PR makes it so stage video is used only when it's supported.  

The use of Stage Video would be nice, as it can pretty dramatically reduces CPU usage.  Adobe even managed to write something about it this year, http://blogs.adobe.com/flashplayer/2015/04/best-practices-for-high-performing-and-efficient-flash-video.html

My big concern would be with overlaying HTML on the video, especially if the "direct" wmode is used.  I would suggest not changing the wmode and going with the lower support you get in browsers when you keep the wmode the same.  But even with that, I would be concerned that this could change something without some good testing in different browsers, as Stage Video can be an odd beast (in my distant years past experience) when it comes to overlaying anything on top of it.

**Comment by benjipott** [comment]
StageVideo is only used if available. But actually in chrome it's broken. the benefit is 80% cpu. 
https://helpx.adobe.com/flash/kb/flash-object-embed-tag-attributes.html

on firefox, transparency is impossible for the element over the player (controlbar bigplaybutton)
so ... :) no benefits

**Comment by forbesjo** [comment]
Thank you very much for this PR but we see Flash as a legacy playback engine that is becoming less important in video.js. This will be complex change and we don't want to introduce complexity into a component we are looking to deprecate in the future.

**Pull request closed without merging**
