### PR TITLE
Add getVideoPlaybackQuality API

### PR DESCRIPTION
**Pull request by gesinger**

### CODE REVIEW

**Comment by mjneil** [comment]
Does flash have a notion of `corruptedVideoFrames`?

Also what about the `creationTime` property? Is the plan to have the `VideoPlaybackQuality` plugin handle that property?

**Comment by gesinger** [comment]
After more discussion, `creationTime` will be added, but will be added from the JS level, since it needs to be relative to the time origin (https://w3c.github.io/hr-time/#time-origin).

**Comment by mjneil** [comment]
LGTM

**Comment by zhuangs** [comment]
Tested and LGTM!

**Comment by imbcmdth** [comment]
Check on Firefox!

**Comment by gesinger** [comment]
Works on Firefox 👍

**Pull request merged**
