### PR TITLE
FCSubscribe support

### PR DESCRIPTION
**Pull request by cladera**
Implements FCSubscribe, required by CDNs such as Akamai, Edgecast or Limelight

### CODE REVIEW

**Comment by cladera** [comment]
Sorry for the mess with the blank lines :( . I'll try to fix it.

**Comment by forbesjo** [comment]
Sorry for not responding to this for a while could you rebase this?

**Comment by cladera** [comment]
I just rebased master branch

**Comment by 5c0rp5** [comment]
Was this ever implemented in the distribution version? I am using versions 5.19.0 and 5.19.1 getting error NetConnection.Call.Failed as described (and hinted to function missing in source code) here: http://stackoverflow.com/questions/24493523/why-can-flash-plyer-not-play-rtmp-live-stream

Im looking at the Video-js.swf source code from my version, and the FCSubscribe function is nowhere to be found.

**Pull request closed without merging**
