### PR TITLE
Live streams now return -1 for duration instead of 0

### PR DESCRIPTION
**Pull request by tjenkinson**
This is currently untested as I can't get the grunt build script to work at the moment.

### CODE REVIEW

**Comment by dmlap** [comment]
The HTML spec says live streams should have a [duration of Infinity](https://html.spec.whatwg.org/multipage/embedded-content.html#dom-media-duration). Would that value work better than zero for you?

**Comment by Animaleante** [comment]
Why was this patch not merged with master yet?

**Comment by EZWrighter** [comment]
Is there a reason this isn't merged?  RTMP is still a very important protocol for live events that you don't want delayed 30+ seconds!

**Comment by gkatsev** [comment]
Given that Adobe Flash is [being end-of-lifes this month](https://www.adobe.com/products/flashplayer/end-of-life.html) we will no longer be working on this repository. Thank you for your contributions.

**Pull request closed without merging**
