### PR TITLE
Added functions for bufferTime, bufferTimeMax and playerStats

### PR DESCRIPTION
**Pull request by sea-kg**
Added functions for bufferTime, bufferTimeMax and playerStats
Fixed bug for bufferEmpty

### CODE REVIEW

**Comment by jgmio** [comment]
Please merge

**Comment by pstoll** [comment]
Please merge this so we can get rid of our custom built swf.

**Comment by pstoll** [comment]
@gkatsev any chance you are still watching this repo? this is a useful, generally benign but super helpful for those of us needing low latency RTMP streaming.

**Comment by gkatsev** [comment]
All these new APIs seem to be RTMP specific, I wonder if they should be named as such.

**Comment by albertogasparin** [comment]
This looks super useful. 
@sea-kg any chance updating the PR to resolve the conflicts?
@gkatsev What do you mean? Could you be more specific? Something like `flashBufferTime` or just a prop in the `flashvars` object?

**Comment by gkatsev** [comment]
@albertogasparin yeah, maybe. Since it won't ever be used by the HTTPVideoProvider.

**Comment by gkatsev** [comment]
Looks like #207 calls it `rtmpBufferTime`.

**Comment by gkatsev** [comment]
Are these things that you'd want to change at runtime? If so, I think I would prefer the #207 approach better.

**Comment by Marcello09** [comment]
Will it ever be merged?

**Comment by sea-kg** [comment]
I think that no

**Pull request closed without merging**
