### PR TITLE
Fixes issues in HTTPAudioProvider.

### PR DESCRIPTION
**Pull request by shenjunru**
Now the flash fallback can play/pause/resume audio source.

### CODE REVIEW

**Comment by heff** [comment]
Cool, thank you! Do you have a live example of this working? I haven't seen the audio functionality of the Flash player used in a while but it would be great if it were working smoothly.

**Comment by shenjunru** [comment]
I have built a swf file on my github. Tested with `video.dev.js` in the `video.js` stable branch.
Here is the demo:
```html
<audio id="el_player" class="vjs-default-skin" controls preload>
  <source src="demo.mp3" type="audio/mpeg">
</audio>
<script>
  videojs.Flash.formats['audio/mpeg'] = 'MP3';
  media = videojs(el_player, {
    'techOrder': [ 'flash' ],
    'flash': {
      'flashVars': { 'mode': 'audio' },
      // this url does not work here... please put it on your server
      'swf': 'https://github.com/shenjunru/video-js-swf/raw/master/dist/video-js.swf'
    }
  });
</script>
```

**Comment by shenjunru** [comment]
Just another suggestion for `video.js` compression.
Try `https://github.com/mishoo/UglifyJS2` instead of `Google Compiler`.
`Compiler` compresses all the properties names.
In some cases, it will be default to use same custom code on dev and prod env.

**Comment by forbesjo** [comment]
@shenjunru Sorry for not responding to this previously, could you rebase this? Thanks!

**Comment by gkatsev** [comment]
Given that Adobe Flash is [being end-of-lifes this month](https://www.adobe.com/products/flashplayer/end-of-life.html) we will no longer be working on this repository. Thank you for your contributions.

**Pull request closed without merging**
