### PR TITLE
Let js fire "seeking"

### PR DESCRIPTION
**Pull request by dmlap**
The flash tech has all the information necessary to fire "seeking" and is much easier to validate. Remove this logic from the SWF and let the js wrapper handle it.

### CODE REVIEW

**Comment by gkatsev** [comment]
LGTM

**Comment by heff** [comment]
This is gonna require a major release of the swf, so we'll need to figure out how we're gonna handle that.

**Comment by gkatsev** [comment]
A major release of the swf doesn't necessarily mean a major release of videojs. Though, since we're updating it as part of 5.0, sounds alright to me.

**Comment by heff** [comment]
Yeah, I'm not worried about video.js for this. More interested in if we're locking down swf-4.x or if we're going to continue to patch it.

**Comment by dmlap** [comment]
I think we might as well do a major release of the SWF for vjs5. I don't think I'll be able to port contrib-hls to a source handler without making this sort of adjustment or adding a whole bunch of hooks into the source handler API to intercept things like seeking. Based on our previous discussions, intercepting all the tech methods doesn't seem like the our preferred route.

**Comment by gkatsev** [comment]
I'm ok with locking down the swf for vjs-4.x. Though, @bclwhitaker might have a different answer :)

**Comment by dmlap** [comment]
Based on the comments in this thread, we're going to merge this into master (starting vjs-swf 5.x) and make stable the 4.x branch until video.js 5.0 is released.

**Pull request merged**
