### PR TITLE
Do not set current time to 0 at end of video

### PR DESCRIPTION
**Pull request by bc-bbay**

### CODE REVIEW

**Comment by gkatsev** [comment]
Can you provide more background on why this change is necessary?

**Comment by bc-bbay** [comment]
In the current swf, if the video ends and then you seek back to, say, 2:00, and hit play, the video will start playing from 0:00 but with a timestamp of 2:00. The result is that any further seeking is broken and eventually the player runs off the end of the progress bar.

This PR fixes that issue.

**Comment by bclwhitaker** [comment]
@bc-bbay Do you have a good understanding of why this code was ever necessary and why it would no longer be now?

@dmlap Looks like this was added in https://github.com/videojs/video-js-swf/commit/c6ccbc7106712f7c3264e3ff09b3fd765f4f6e44 .  Do you recall if it was addressing a specific issue that should be retested with this change in place?

**Comment by dmlap** [comment]
@bclwhitaker If you test this change against videojs-contrib-hls and it doesn't regress anything, LGTM

**Comment by bc-bbay** [comment]
I have tested and see no regressions. Pulling it in!

**Pull request merged**
