### PR TITLE
Fix two-clicks to play back issue when preload was not "auto"

### PR DESCRIPTION
**Pull request by bclwhitaker**
If preload was anything other than auto, we were exiting after just initializing the connection on first play attempts. This means you have to click twice to start playback.  Make sure we actually start playback whenever play is called.

### CODE REVIEW

**Comment by heff** [comment]
So `_ns.resume();` won't throw an error if initNetConnection hasn't happened yet?

Otherwise looks good to me. Thanks for putting this together.

**Comment by bclwhitaker** [comment]
Because initNetConnection sets the `_loadStarted = true;` I don't think you can get to here without initNetConnection being called.

**Comment by heff** [comment]
It looks like this PR moves the chunk of code with `_ns.resume()` out of the `if (!_loadStarted) {} else {` block, meaning resume would be called every time play() is called, even if loadStarted was false. Am I reading it wrong? It might not do anything bad but thought it was worth calling it out to make sure.

**Comment by bclwhitaker** [comment]
Yea, because its asynchronous I can see `_ns.resume()` being called before the `_ns` is defined/initialized with this code.  

I also think `ExternalEventName.ON_RESUME` and `ExternalEventName.ON_STREAM_START` would trigger twice as it stood because of this code:
https://github.com/videojs/video-js-swf/blob/master/src/com/videojs/providers/HTTPVideoProvider.as#L536-L539

I think I have addressed both of these issues.

**Comment by heff** [comment]
Awesome, thanks. LGTM! Probably worth getting one other set of eyes on this if it's just been you and me so far.

**Comment by bclwhitaker** [comment]
@bc-bbay ?

**Comment by bc-bbay** [comment]
LGTM!

**Pull request merged**
