### PR TITLE
Added bufferTimeMax set 1 (for RTMPVideoProvider)

### PR DESCRIPTION
**Pull request by sea-kg**
For low latancy

### CODE REVIEW

**Comment by pstoll** [comment]
Similar to https://github.com/videojs/video-js-swf/pull/207 it might be cleaner to allow this to be configured via the VideoJS configuration (vs hard coding it). Although I'd prefer a default of 1 vs 0 for now, too.

**Comment by jgmio** [comment]
Any news on this?

**Comment by sea-kg** [comment]
Implemented in another fork: https://github.com/VideoExpertsGroup/video-js-swf  but there has not only for buffertime

**Comment by sea-kg** [comment]
If you wish I can prepare another pull request with this feature

**Comment by jgmio** [comment]
I don't wish to impose but I can't say I would really like this feature

**Comment by sea-kg** [comment]
Anywhere I created new pull request...

**Comment by jgmio** [comment]
Sweet, thank you

**Pull request closed without merging**
